# Generated by Django 5.2.1 on 2025-05-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
